apiVersion: instana.io/v1beta2
kind: Core
metadata:
  namespace: instana-core
  name: instana-core
spec:
  # Base domain for Instana
  baseDomain:

  # Host and port for the agent acceptor, usually a subdomain of the base domain
  agentAcceptorConfig:
    host:
    port: 443

  # dockerRegistryURI: containers.instana.io

  # URL for downloading the GeoLite2 geo-location data file
  # geoDbUrl:

  # Datastore configs
datastoreConfigs:
  cassandraConfigs:
    - hosts:
        - <cassandra hosts or IPs>
  clickhouseConfigs:
    - hosts:
        - <clickhouse hosts or IPs>
  cockroachdbConfigs:
    - hosts:
        - <cockroachdb hosts or IPs>
  elasticsearchConfig:
    hosts:
      - <elasticsearch hosts or IPs>
  kafkaConfig:
    hosts:
      - <kafka hosts or IPs>

  # Use one of smtpConfig or sesConfig
  # emailConfig:
    # smtpConfig:
    #   from:
    #   host:
    #   port:
    #   useSSL: true

    # sesConfig:
    #   from:
    #   region:
    #   returnPath:

  # storageConfigs:
  #   Use either s3Config, gcloudConfig, or pvcConfig

  #   ## External Storage for raw spans ##
  #   rawSpans:
  #     s3Config:
  #       bucket:
  #       bucketLongTerm:
  #       endpoint:
  #       prefix:
  #       prefixLongTerm:
  #       region:
  #       storageClass:
  #       storageClassLongTerm:
  #       accessKeyId:
  #       secretAccessKey:

  #     gcloudConfig:
  #       bucket:
  #       bucketLongTerm:
  #       prefix:
  #       prefixLongTerm:
  #       storageClass:
  #       storageClassLongTerm:
  #       serviceAccountKey:

  #     pvcConfig:
  #       accessModes:
  #         - ReadWriteMany
  #       resources:
  #         requests:
  #           storage: 100Gi
  #       storageClassName: my-fast-storage

  #   ## External Storage for synthetics test results ##
  #   synthetics:
  #     s3Config:
  #       bucket:
  #       bucketLongTerm:
  #       endpoint:
  #       prefix:
  #       prefixLongTerm:
  #       region:
  #       storageClass:
  #       storageClassLongTerm:
  #       accessKeyId:
  #       secretAccessKey:

  #     gcloudConfig:
  #       bucket:
  #       bucketLongTerm:
  #       prefix:
  #       prefixLongTerm:
  #       storageClass:
  #       storageClassLongTerm:
  #       serviceAccountKey:

  #     pvcConfig:
  #       accessModes:
  #         - ReadWriteMany
  #       resources:
  #         requests:
  #           storage: 100Gi
  #       storageClassName: my-fast-storage

  # Service provider configs for SAML or OIDC
  # serviceProviderConfig:
    # Base URL (defaults to "/auth")
    # basePath:

    # The maximum IDP metadata size (defaults to 200000)
    # maxAuthenticationLifetimeSeconds:

    # The maximum authentication lifetime (defaults to 604800)
    # maxIDPMetadataSizeInBytes:
