apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: openshift-gitops
  name: namespaces
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  destination:
    namespace: instana
    server: https://kubernetes.default.svc
  project: instana
  source:
    repoURL: https://github.com/thomas-mattsson/instana-gitops
    path: components/instana-operator/base
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
